universe = vanilla
executable = run_mcpana.sh
arguments = $(name) $(nev) $(extra) $(files) $(cfg)
transfer_input_files = mcpana_ship.tgz,golden24.tgz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = output
use_x509userproxy = True
x509userproxy = $ENV(X509_USER_PROXY)
request_memory = 3500
request_cpus = 1
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel8"
output = logs/$(name).out
error = logs/$(name).err
log = logs/condor.log
queue name,nev,extra,files,cfg from $(joblist)
